### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by sec13b** [Gh0st-D3V/Knocker#1]
Missing GOOSE.py  😄

**Comment by Gh0st-D3V** [comment]
GOOSE.py has its own repository on my git hub, but thanks for bringing this to my attention, will have an update soon.

**Comment by Gh0st-D3V** [comment]
GOOSE.py has its own repository, but thank you for bringing this to my attention, fix will come soon

**Comment by Gh0st-D3V** [comment]
GOOSE.py has now been added to knocker repository
